### PR TITLE
added test coverage

### PR DESCRIPTION
**Pull request by tobilott5**

### CODE REVIEW

**Comment by hergin** [comment]
You didn't update your github actions file to replace npm test with coverage one

**Comment by tobilott5** [comment]
> You didn't update your github actions file to replace npm test with coverage one

Yeah sorry, when i changed the node.js.yml file it created a second branch for it. Should I find a way to combine the two branches?

**Comment by hergin** [comment]
You can do the second change in this branch again. It will automatically get it.

**Comment by tobilott5** [comment]
> You can do the second change in this branch again. It will automatically get it.

it should be all here now

**Review by hergin — APPROVED** [review]

**Review by SaltyTea4924 — COMMENTED** [review]
done

**Review by SaltyTea4924 — APPROVED** [review]

**Pull request merged**
